server:
  port: 8080
  
logging:
  file: log.log

eureka:
  instance:
    healthCheckUrlPath: ${management.contextPath}/health
    metadata-map:
      management.context-path: "${management.contextPath}"
  client:
    props: 
    serviceUrl:
      defaultZone: http://admin:admin@ec2-13-59-80-6.us-east-2.compute.amazonaws.com:8761/eureka/

zuul:
  sensitiveHeaders:
  routes:
    uaa-service:
      sensitiveHeaders:
      path: /uaa/**
      stripPrefix: false
    account-service:
      sensitiveHeaders:
      path: /accounts/**
      stripPrefix: true
    order-service:
      sensitiveHeaders:
      path: /orders/**
      stripPrefix: false

hystrix:
  command:
    uaa-service:
      execution:
        timeout:
          enabled: false
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
            
security:
  basic:
    enabled: false
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0DsrJige51wEhIDatvnq
          zGlrb+HGZmUCB7UxxoP7m+humK6paRilkpKKXoJeiwrYz2Cx9dLG1Q0IxtOlxPU4
          RsCjFw3N8hrmuw+R8Fn6d0wAXUFR3EjoyiNaGK++2RaTEsbzK1A1/ea6DKH1UuFB
          +NL1BQacKtQH3mwe/7ot9uW1axKwb28cqxHBYwxIdK8gQumCrLdwd9d+ZFn6j+7z
          9VszKolOnmkeo1bOFNGBJ2Vf4b6XQc/uukpSDmV2l2pLMQ/DVLWvU/cl9Wd7S8CQ
          pIQiKzmnKlbvM18EVDZwb0vcXZenT5yGHZ3GHXEJDzChnRbQtQOjvUvKzPnoBzGx
          7wIDAQAB
          -----END PUBLIC KEY-----
          
management:
  contextPath: /mgmt
  security:
    enabled: false
    
endpoints:
  enabled: false
  health.enabled: true
  info.enabled: true
  logfile.enabled: true
  loggers.enabled: true
  metrics.enabled: true
  trace.enabled: true
  
  
---

spring:
  profiles: dev
  
eureka:
  instance:
    hostname: localhost
    port: 8761
    healthCheckUrlPath: ${management.contextPath}/health
    metadata-map:
      management.context-path: "${management.contextPath}"
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka
