server:
  port: 8080

eureka:
  instance: 
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

zuul:
  routes:
    uaa-service:
      sensitiveHeaders:
      path: /uaa/**
      stripPrefix: false
    account-service:
      sensitiveHeaders:
      path: /accounts/**
      stripPrefix: true
    order-service:
      sensitiveHeaders:
      path: /orders/**
      stripPrefix: true
  add-proxy-headers: true

hystrix:
  command:
    uaa-service:
      execution:
        timeout:
          enabled: false
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
