server:
  port: 8080

eureka:
  instance: 
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

zuul:
  routes:
    rest-api: 
      sensitiveHeaders: 
      path: /api/**
      stripPrefix: false
    uaa-service:
      sensitiveHeaders:
      path: /uaa/**
      stripPrefix: false
  add-proxy-headers: true

hystrix:
  command:
    uaa-service:
      execution:
        timeout:
          enabled: false
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
